spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "2.1"

accounts:
  message: "Live - Bank Accounts APIs"
  contactDetails:
    name: "Derek - Prod Support"
    email: "derek.prod@example.com"
  onCallSupport:
    - "+91 9517538520"
    - "+91 8521479630"
