spring:
   datasource:
    url: jdbc:mysql://localhost:3306/cards
    username: root
    password: chutiya22
    driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9000

  config:
    import:
      - application-qa.yml
      - application-prod.yml
  profiles:
    active:
      - "qa"

build:
  version: "3.0"

cards:
  message: "welcome to Bank Cards related local APIs"
  contactDetails:
    name: "naveen negi"
    email: "nav45@fkd.com"
  onCallSupport:
    - 31321321231321
    - 54546465464544


