version: "3.8"

services:
  accounts:
    image: "raznegi69/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - raznegi69

  cards:
    image: "raznegi69/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - raznegi69

  loans:
    image: "raznegi69/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - raznegi69

networks:
  raznegi69:
    driver: bridge
