
spring:
   application:
    name: "gatewayserver"
   config:
    import:
    - "optional:configserver:http://localhost:8071/"
   cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 3s

   data:
     redis:
       connect-timeout: 2s
       host: localhost
       port: 6379
       timeout: 1s
      

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    gateway:
      access: unrestricted

  info:
    env:
      enabled: true


info:
  app:
    name: "gatewayserver"
    description: "Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      raz:
        gatewayserver: DEBUG


resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000

      