spring:
   application:
    name: "loans"
   profiles:
    active: "prod"
   datasource:
    url: jdbc:mysql://localhost:3306/loans
    username: root
    password: chutiya22
    driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
   config:
    import:
    - "optional:configserver:http://localhost:8071/"
   
   rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
    
server:
  port: 8090


management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
