spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "3.1"

accounts:
  message: "Testing Mode - Accounts APIs"
  contactDetails:
    name: "Frank - QA Lead"
    email: "frank.local@example.com"
  onCallSupport:
    - "+91 1112223334"
    - "+91 5556667778"
