build:
  version: "1.2"

accounts:
  message: "Testing Mode - Accounts APIs"
  contactDetails:
    name: "Charlie - QA Lead"
    email: "charlie.qa@example.com"
  onCallSupport:
    - "+91 7418529630"
    - "+91 3692581470"
