build:
  version: "1.2"

accounts:
  message: "Welcome to Bank Accounts related prod APIs"
  contactDetails:
    name: "Charlie - prod Lead"
    email: "charlie.qa@example.com"
  onCallSupport:
    - "+91 7418529630"
    - "+91 3692581470"
