spring:
   application:
    name: "accounts"
   profiles:
    active:
    - "prod"
   datasource:
    url: jdbc:mysql://host.docker.internal:3306/accounts
    username: root
    password: chutiya22
    driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect 
   config:
    import:
    - "optional:configserver:http://localhost:8071/"
   rabbitmq:
    host: "localhost"
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
