server:
  port: 8080
spring:
   application:
    name: "accounts"
   profiles:
    active:
    - "prod"
   datasource:
    url: jdbc:mysql://localhost:3306/accounts
    username: root
    password: chutiya22
    driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect 
   config:
    import:
    - "optional:configserver:http://localhost:8071/"
   cloud:
     openfeign:
       circuitbreaker:
         enabled: true
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      applications: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "Bank Accounts Application"
    version: "1.0.0"

logging:
  level:
    com:
      raz:
        accounts: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000

  retry:
    configs:
      default:
        max-attempts: 5
        wait-duration: 100
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        ignore-exceptions:
          - java.lang.NullPointerException
        retry-exceptions:
          - java.util.concurrent.TimeoutException

  ratelimiter:
    configs:
      default:
        timeout-duration: 1000
        limit-refresh-period: 5000
        limit-for-period: 1
      