spring:
  application:
    name: "configserver"
  profiles:
    active:
      - git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RAVINDRA-NEGI/bank-config.git
          default-label: main
          timeout: 5
          clone-on-start: true 
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
 

encrypt:
  key: "NtvtU5n16yWkk03a0T3rqA=="

server:
  port: 8071
