spring:
  application:
    name: "configserver"
  profiles:
  #active: native
    active:
    - git
  cloud:
    config:
      server:
       # native:
          #search-locations:
          #- "classpath:/config"
         git:
          uri: git@github.com:RAVINDRA-NEGI/bank-config.git
          default-label: main
          timeout: 5
          clone-on-start: true 
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

encrypt:
  key: "NtvtU5n16yWkk03a0T3rqA=="


server:
  port: 8071