server:
  port: 9010

spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email|sms
logging:
  level:
    org.springframework.cloud.function.context.catalog.FunctionInspector: DEBUG
